/* ===========================================================================
   dex-more-2.js — the rest of Johto, Hoenn and Sinnoh
   =========================================================================== */
(function () {
  "use strict";
  const m = (name, type, power) => ({ name, type, power });

  window.DEX.add([
    /* ======================= JOHTO ======================= */
    { id: 'meganium', name: 'Meganium', region: 'johto', dex: 154, types: ['Grass'],
      hp: 100, atk: 82, def: 100, spd: 80,
      abilities: ['Overgrow — when it is hurt, its grass moves get stronger', 'Leaf Guard — sunshine keeps it from getting sick'],
      fact: 'The scent from its flower calms angry Pokemon down and brings dead grass back to life.',
      moves: [m('Razor Leaf', 'Grass', 55), m('Body Slam', 'Normal', 85), m('Energy Ball', 'Grass', 90), m('Petal Blizzard', 'Grass', 90)],
      art: { shape: 'quad', body: '#a8e6a0', accent: '#7fc87f', belly: '#d8f5cc', ears: 'none', tail: 'none', front: ['headLeaf', 'leafBow'], eyes: 'happy', mouth: 'smile' } },

    { id: 'typhlosion', name: 'Typhlosion', region: 'johto', dex: 157, types: ['Fire'],
      hp: 98, atk: 109, def: 78, spd: 100,
      abilities: ['Blaze — when it is hurt, its fire moves get stronger', 'Flash Fire — fire attacks make it stronger, not weaker'],
      fact: 'It hides behind a shimmer of heat haze, then makes a blast of fire that burns everything to nothing.',
      moves: [m('Flame Wheel', 'Fire', 60), m('Crunch', 'Dark', 80), m('Flamethrower', 'Fire', 90), m('Eruption', 'Fire', 110)],
      art: { shape: 'biped', body: '#3f6fa8', accent: '#2f5688', belly: '#f5e0a8', ears: 'none', tail: 'thin', back: ['backFlames'], eyes: 'angry', mouth: 'fangs' } },

    { id: 'feraligatr', name: 'Feraligatr', region: 'johto', dex: 160, types: ['Water'],
      hp: 100, atk: 105, def: 90, spd: 78,
      abilities: ['Torrent — when it is hurt, its water moves get stronger', 'Sheer Force — it ignores luck and just hits harder'],
      fact: 'It is heavy and slow on land, but it kicks off its back legs and charges faster than you can run.',
      moves: [m('Bite', 'Dark', 60), m('Aqua Tail', 'Water', 90), m('Crunch', 'Dark', 80), m('Hydro Pump', 'Water', 110)],
      art: { shape: 'biped', body: '#4fb8e8', accent: '#2f96c8', belly: '#f5d76e', ears: 'none', tail: 'thin', back: ['spikes'], front: ['fangsBig'], eyes: 'angry', mouth: 'fangs' } },

    { id: 'pichu', name: 'Pichu', region: 'johto', dex: 172, types: ['Electric'],
      hp: 50, atk: 40, def: 30, spd: 60,
      abilities: ['Static — anyone who touches it might get zapped', 'Lightning Rod — it soaks up electric attacks instead of being hurt'],
      fact: 'It is not very good at holding its electricity in yet, so it zaps itself by accident when surprised.',
      moves: [m('Thunder Shock', 'Electric', 40), m('Nuzzle', 'Electric', 40), m('Sweet Kiss', 'Fairy', 40), m('Quick Attack', 'Normal', 40)],
      art: { shape: 'biped', body: '#f7e07a', accent: '#e0c040', belly: '#fff6c8', cheek: '#ef6b63', ears: 'point', earTip: '#2b2b3a', tail: 'zigzag', front: ['cheeks'], eyes: 'big', mouth: 'w' } },

    { id: 'mareep', name: 'Mareep', region: 'johto', dex: 179, types: ['Electric'],
      hp: 65, atk: 50, def: 45, spd: 42,
      abilities: ['Static — anyone who touches it might get zapped', 'Plus — it works better with a partner'],
      fact: 'Rubbing its wool makes sparks, and the more electricity it stores the brighter its tail glows.',
      moves: [m('Tackle', 'Normal', 40), m('Thunder Shock', 'Electric', 40), m('Spark', 'Electric', 65), m('Discharge', 'Electric', 80)],
      art: { shape: 'blob', body: '#f7f2e4', accent: '#f5d76e', belly: '#fffdf5', ears: 'long', earTip: '#f5d76e', tail: 'star', back: ['fluff'], eyes: 'happy', mouth: 'smile' } },

    { id: 'ampharos', name: 'Ampharos', region: 'johto', dex: 181, types: ['Electric'],
      hp: 90, atk: 95, def: 85, spd: 55,
      abilities: ['Static — anyone who touches it might get zapped', 'Plus — it works better with a partner'],
      fact: 'Its tail shines so brightly it can be seen from space — people once used it as a lighthouse.',
      moves: [m('Thunder Shock', 'Electric', 40), m('Power Gem', 'Rock', 80), m('Thunderbolt', 'Electric', 90), m('Thunder', 'Electric', 110)],
      art: { shape: 'biped', body: '#f7d060', accent: '#e8704a', belly: '#fff6d8', ears: 'round', earTip: '#2b2b3a', tail: 'star', front: ['gem'], eyes: 'round', mouth: 'smile' } },

    { id: 'azumarill', name: 'Azumarill', region: 'johto', dex: 184, types: ['Water', 'Fairy'],
      hp: 100, atk: 50, def: 80, spd: 50,
      abilities: ['Huge Power — its little arms are twice as strong as they look', 'Thick Fat — fire and ice attacks hurt it only half as much'],
      fact: 'It squeezes air into a bubble balloon so smaller Pokemon can breathe underwater with it.',
      moves: [m('Bubble Beam', 'Water', 65), m('Play Rough', 'Fairy', 70), m('Aqua Tail', 'Water', 90), m('Body Slam', 'Normal', 85)],
      art: { shape: 'blob', body: '#7fd0f0', accent: '#5fb0d8', belly: '#ffffff', ears: 'round', earTip: '#ffffff', tail: 'swirl', front: ['spots'], eyes: 'happy', mouth: 'smile' } },

    { id: 'espeon', name: 'Espeon', region: 'johto', dex: 196, types: ['Psychic'],
      hp: 65, atk: 130, def: 60, spd: 110,
      abilities: ['Synchronize — whatever bad thing happens to it happens to the attacker too', 'Magic Bounce — it reflects moves straight back'],
      fact: 'The fine hairs on its fur read the air, so it can tell what you are feeling and what you will do next.',
      moves: [m('Confusion', 'Psychic', 50), m('Swift', 'Normal', 65), m('Psybeam', 'Psychic', 65), m('Psychic', 'Psychic', 100)],
      art: { shape: 'quad', body: '#e8a8c8', accent: '#d090b0', belly: '#f5d8e8', cheek: '#ef6b63', ears: 'point', earTip: '#d090b0', tail: 'fan', front: ['gem'], eyes: 'sleepy', mouth: 'none' } },

    { id: 'larvitar', name: 'Larvitar', region: 'johto', dex: 246, types: ['Rock', 'Ground'],
      hp: 70, atk: 74, def: 60, spd: 41,
      abilities: ['Guts — feeling poorly makes it punch harder', 'Sand Veil — it is hard to hit in a sandstorm'],
      fact: 'It is born deep underground and has to eat a whole mountain of soil before it can evolve.',
      moves: [m('Bite', 'Dark', 60), m('Rock Slide', 'Rock', 75), m('Crunch', 'Dark', 80), m('Earthquake', 'Ground', 95)],
      art: { shape: 'blob', body: '#8ac8a0', accent: '#6aa880', belly: '#b8e0c8', ears: 'none', tail: 'none', front: ['plates'], eyes: 'round', mouth: 'smile' } },

    { id: 'tyranitar', name: 'Tyranitar', region: 'johto', dex: 248, types: ['Rock', 'Dark'],
      hp: 120, atk: 134, def: 110, spd: 61,
      abilities: ['Sand Stream — a sandstorm whips up the moment it arrives', 'Unnerve — the other Pokemon is too nervous to eat its berry'],
      fact: 'It can knock down a mountain to make itself a nest, and maps have to be redrawn after it moves.',
      moves: [m('Crunch', 'Dark', 80), m('Rock Slide', 'Rock', 75), m('Earthquake', 'Ground', 100), m('Stone Edge', 'Rock', 110)],
      art: { shape: 'biped', body: '#8ac8a0', accent: '#4a7a5a', belly: '#c8e0b0', ears: 'point', earTip: '#4a7a5a', tail: 'thin', back: ['plates'], front: ['fangsBig'], eyes: 'angry', mouth: 'fangs' } },

    { id: 'lugia', name: 'Lugia', region: 'johto', dex: 249, types: ['Psychic', 'Flying'], legend: true,
      hp: 126, atk: 105, def: 130, spd: 110,
      abilities: ['Pressure — the Pokemon facing it gets tired faster', 'Multiscale — at full health, everything hurts it half as much'],
      fact: 'It sleeps at the bottom of the sea because a single flap of its wings can blow houses apart.',
      moves: [m('Aeroblast', 'Flying', 100), m('Psychic', 'Psychic', 90), m('Hydro Pump', 'Water', 110), m('Ancient Power', 'Rock', 60)],
      art: { shape: 'bird', body: '#f0f4fa', accent: '#7f9ed8', belly: '#ffffff', beak: '#c8d4e8', wing: '#a8bde0', ears: 'none', tail: 'fan', back: ['bigWings'], front: ['beak', 'crest'], eyes: 'sleepy', mouth: 'none' } },

    { id: 'hooh', name: 'Ho-Oh', region: 'johto', dex: 250, types: ['Fire', 'Flying'], legend: true,
      hp: 126, atk: 130, def: 110, spd: 90,
      abilities: ['Pressure — the Pokemon facing it gets tired faster', 'Regenerator — it heals a little every time it swaps out'],
      fact: 'Its feathers glow in seven colours, and anyone who sees it flying is promised happiness forever.',
      moves: [m('Sacred Fire', 'Fire', 100), m('Air Slash', 'Flying', 75), m('Brave Bird', 'Flying', 120), m('Ancient Power', 'Rock', 60)],
      art: { shape: 'bird', body: '#f0863a', accent: '#f5b700', belly: '#ffe0a0', beak: '#f5c040', wing: '#e8553a', ears: 'none', tail: 'fan', back: ['bigWings'], front: ['beak', 'crest'], eyes: 'round', mouth: 'none' } },

    { id: 'celebi', name: 'Celebi', region: 'johto', dex: 251, types: ['Psychic', 'Grass'], legend: true,
      hp: 110, atk: 100, def: 100, spd: 100,
      abilities: ['Natural Cure — swapping out cures anything making it ill', 'Time Travel — it can slip forwards and backwards through time'],
      fact: 'It travels through time, and wherever it appears the forest bursts into life.',
      moves: [m('Magical Leaf', 'Grass', 60), m('Psychic', 'Psychic', 90), m('Energy Ball', 'Grass', 90), m('Ancient Power', 'Rock', 60)],
      art: { shape: 'humanoid', body: '#a8e07a', accent: '#7fc050', belly: '#d8f0b0', ears: 'leaf', earTip: '#7fc050', tail: 'none', back: ['sparkles', 'wings'], wing: '#d8f0a0', eyes: 'happy', mouth: 'smile' } },

    /* ======================= HOENN ======================= */
    { id: 'sceptile', name: 'Sceptile', region: 'hoenn', dex: 254, types: ['Grass'],
      hp: 90, atk: 105, def: 75, spd: 120,
      abilities: ['Overgrow — when it is hurt, its grass moves get stronger', 'Unburden — it gets twice as fast once it drops its item'],
      fact: 'The leaves on its arms are sharper than swords, and it leaps between branches faster than the eye can follow.',
      moves: [m('Leaf Blade', 'Grass', 90), m('Dragon Claw', 'Dragon', 80), m('Energy Ball', 'Grass', 90), m('Quick Attack', 'Normal', 40)],
      art: { shape: 'biped', body: '#7ec87e', accent: '#5ba85b', belly: '#f08080', ears: 'leaf', earTip: '#5ba85b', tail: 'fan', back: ['spikes'], eyes: 'angry', mouth: 'smirk' } },

    { id: 'blaziken', name: 'Blaziken', region: 'hoenn', dex: 257, types: ['Fire', 'Fighting'],
      hp: 90, atk: 120, def: 70, spd: 80,
      abilities: ['Blaze — when it is hurt, its fire moves get stronger', 'Speed Boost — it gets faster every single turn'],
      fact: 'Its kicks come wrapped in flame, and it can jump clean over a thirty-storey building.',
      moves: [m('Flame Charge', 'Fire', 50), m('Blaze Kick', 'Fire', 85), m('Sky Uppercut', 'Fighting', 85), m('Flare Blitz', 'Fire', 110)],
      art: { shape: 'humanoid', body: '#e8553a', accent: '#f5d76e', belly: '#f7a83a', ears: 'none', tail: 'fan', front: ['headTuft'], eyes: 'angry', mouth: 'none' } },

    { id: 'swampert', name: 'Swampert', region: 'hoenn', dex: 260, types: ['Water', 'Ground'],
      hp: 100, atk: 110, def: 90, spd: 60,
      abilities: ['Torrent — when it is hurt, its water moves get stronger', 'Damp — it soaks the ground so explosions cannot happen'],
      fact: 'It is strong enough to drag a boulder, and it can feel a storm coming a day before it arrives.',
      moves: [m('Mud Shot', 'Ground', 55), m('Surf', 'Water', 90), m('Earthquake', 'Ground', 100), m('Hydro Pump', 'Water', 110)],
      art: { shape: 'biped', body: '#5fa8c8', accent: '#f0772b', belly: '#c8e8f0', ears: 'none', tail: 'fan', front: ['cheekFins', 'fangsBig'], eyes: 'angry', mouth: 'none' } },

    { id: 'kirlia', name: 'Kirlia', region: 'hoenn', dex: 281, types: ['Psychic', 'Fairy'],
      hp: 68, atk: 65, def: 55, spd: 70,
      abilities: ['Synchronize — it shares whatever it is feeling with everyone nearby', 'Trace — it copies the ability of the Pokemon it is facing'],
      fact: 'When its trainer is happy it spins and dances, and the spinning warps the air around it.',
      moves: [m('Confusion', 'Psychic', 50), m('Draining Kiss', 'Fairy', 50), m('Psybeam', 'Psychic', 65), m('Dazzling Gleam', 'Fairy', 80)],
      art: { shape: 'humanoid', body: '#f4f4f8', accent: '#7ec87e', belly: '#ffffff', cheek: '#ef6b63', ears: 'leaf', earTip: '#7ec87e', tail: 'none', front: ['gem'], eyes: 'sleepy', mouth: 'none' } },

    { id: 'gardevoir', name: 'Gardevoir', region: 'hoenn', dex: 282, types: ['Psychic', 'Fairy'],
      hp: 88, atk: 125, def: 85, spd: 80,
      abilities: ['Trace — it copies the ability of the Pokemon it is facing', 'Telepathy — it knows what its partner is about to do'],
      fact: 'It will make a small black hole to protect the person it has decided to look after.',
      moves: [m('Psybeam', 'Psychic', 65), m('Dazzling Gleam', 'Fairy', 80), m('Moonblast', 'Fairy', 95), m('Psychic', 'Psychic', 100)],
      art: { shape: 'humanoid', body: '#f4f4f8', accent: '#7ec87e', belly: '#ffffff', cheek: '#ef6b63', ears: 'none', tail: 'none', front: ['gem'], back: ['aura'], auraColor: '#c8f0c8', eyes: 'sleepy', mouth: 'smile' } },

    { id: 'latias', name: 'Latias', region: 'hoenn', dex: 380, types: ['Dragon', 'Psychic'], legend: true,
      hp: 110, atk: 110, def: 110, spd: 110,
      abilities: ['Levitate — ground moves cannot touch it at all', 'Soul Heart — it is very sensitive to how people feel'],
      fact: 'It is highly intelligent and very shy, and it hides itself by bending the light around it.',
      moves: [m('Dragon Breath', 'Dragon', 60), m('Psychic', 'Psychic', 90), m('Dragon Pulse', 'Dragon', 85), m('Mist Ball', 'Psychic', 95)],
      art: { shape: 'bird', body: '#f0f4fa', accent: '#e8607a', belly: '#ffffff', beak: '#e8607a', wing: '#e8607a', ears: 'none', tail: 'fan', back: ['bigWings'], front: ['beak'], eyes: 'happy', mouth: 'none' } },

    { id: 'latios', name: 'Latios', region: 'hoenn', dex: 381, types: ['Dragon', 'Psychic'], legend: true,
      hp: 110, atk: 120, def: 100, spd: 110,
      abilities: ['Levitate — ground moves cannot touch it at all', 'Sky Speed — it flies faster than a jet plane'],
      fact: 'It can show you pictures in your mind of things it has seen far away.',
      moves: [m('Dragon Breath', 'Dragon', 60), m('Psychic', 'Psychic', 90), m('Dragon Pulse', 'Dragon', 85), m('Luster Purge', 'Psychic', 95)],
      art: { shape: 'bird', body: '#f0f4fa', accent: '#5f8fd8', belly: '#ffffff', beak: '#5f8fd8', wing: '#5f8fd8', ears: 'none', tail: 'fan', back: ['bigWings'], front: ['beak'], eyes: 'round', mouth: 'none' } },

    { id: 'kyogre', name: 'Kyogre', region: 'hoenn', dex: 382, types: ['Water'], legend: true,
      hp: 130, atk: 140, def: 110, spd: 90,
      abilities: ['Drizzle — heavy rain starts pouring the moment it appears', 'Ocean Heart — it can make the whole sea rise'],
      fact: 'It is said to have made the seas, and it can summon rainstorms that flood entire regions.',
      moves: [m('Water Pulse', 'Water', 60), m('Ice Beam', 'Ice', 90), m('Surf', 'Water', 90), m('Origin Pulse', 'Water', 120)],
      art: { shape: 'bigblob', body: '#3f6fc8', accent: '#e8e8f0', belly: '#7f9ed8', ears: 'none', tail: 'fan', front: ['stripes', 'fangsBig'], back: ['flippers'], eyes: 'angry', mouth: 'none' } },

    { id: 'groudon', name: 'Groudon', region: 'hoenn', dex: 383, types: ['Ground'], legend: true,
      hp: 130, atk: 150, def: 140, spd: 90,
      abilities: ['Drought — it makes the sun blaze the moment it appears', 'Land Heart — it can raise new land out of the sea'],
      fact: 'It is said to have made the land, and magma flows in its veins instead of blood.',
      moves: [m('Bulldoze', 'Ground', 60), m('Earthquake', 'Ground', 100), m('Fire Punch', 'Fire', 75), m('Precipice Blades', 'Ground', 120)],
      art: { shape: 'biped', body: '#e8553a', accent: '#4a4a5a', belly: '#f5b8a0', ears: 'none', tail: 'thin', back: ['plates'], front: ['fangsBig'], eyes: 'angry', mouth: 'fangs' } },

    { id: 'rayquaza', name: 'Rayquaza', region: 'hoenn', dex: 384, types: ['Dragon', 'Flying'], legend: true,
      hp: 125, atk: 150, def: 100, spd: 115,
      abilities: ['Air Lock — it switches off all weather completely', 'Sky Guardian — it stops Groudon and Kyogre from fighting'],
      fact: 'It has lived in the ozone layer for hundreds of millions of years and has never once landed.',
      moves: [m('Dragon Claw', 'Dragon', 80), m('Air Slash', 'Flying', 75), m('Dragon Pulse', 'Dragon', 85), m('Dragon Ascent', 'Flying', 120)],
      art: { shape: 'serpent', girth: 20, body: '#3f9e6a', accent: '#f5d76e', belly: '#8ad0a8', ears: 'fin', earTip: '#f5d76e', tail: 'none', front: ['crest', 'fangsBig'], eyes: 'angry', mouth: 'none' } },

    { id: 'jirachi', name: 'Jirachi', region: 'hoenn', dex: 385, types: ['Steel', 'Psychic'], legend: true,
      hp: 110, atk: 100, def: 100, spd: 100,
      abilities: ['Serene Grace — lucky things happen twice as often for it', 'Wish Granter — it grants a wish written on the tags on its head'],
      fact: 'It sleeps for a thousand years at a time, and it grants any wish written on the notes it carries.',
      moves: [m('Confusion', 'Psychic', 50), m('Zen Headbutt', 'Psychic', 80), m('Iron Head', 'Steel', 80), m('Doom Desire', 'Steel', 100)],
      art: { shape: 'humanoid', body: '#f7e07a', accent: '#f5b700', belly: '#fff6c8', crownColor: '#f5b700', ears: 'none', tail: 'none', front: ['crown'], back: ['sparkles'], eyes: 'happy', mouth: 'smile' } },

    /* ======================= SINNOH ======================= */
    { id: 'torterra', name: 'Torterra', region: 'sinnoh', dex: 389, types: ['Grass', 'Ground'],
      hp: 105, atk: 109, def: 105, spd: 56,
      abilities: ['Overgrow — when it is hurt, its grass moves get stronger', 'Shell Armor — it can never be hit by a critical hit'],
      fact: 'Small Pokemon sometimes live their whole lives on its back, thinking it is just a moving hill.',
      moves: [m('Razor Leaf', 'Grass', 55), m('Earthquake', 'Ground', 100), m('Wood Hammer', 'Grass', 110), m('Crunch', 'Dark', 80)],
      art: { shape: 'quad', body: '#7fa858', accent: '#5a7a3a', belly: '#d8c898', shell: '#6a5a3a', shell2: '#8a7a4a', ears: 'none', tail: 'none', back: ['shell'], front: ['headLeaf'], eyes: 'angry', mouth: 'none' } },

    { id: 'infernape', name: 'Infernape', region: 'sinnoh', dex: 392, types: ['Fire', 'Fighting'],
      hp: 88, atk: 104, def: 71, spd: 108,
      abilities: ['Blaze — when it is hurt, its fire moves get stronger', 'Iron Fist — all its punching moves hit harder'],
      fact: 'The flame on its head never goes out, and it fights with all four limbs at once.',
      moves: [m('Flame Wheel', 'Fire', 60), m('Close Combat', 'Fighting', 100), m('Flare Blitz', 'Fire', 110), m('Mach Punch', 'Fighting', 40)],
      art: { shape: 'humanoid', body: '#c07040', accent: '#f5e0a8', belly: '#f5d0a0', ears: 'none', tail: 'flame', front: ['headTuft'], eyes: 'angry', mouth: 'none' } },

    { id: 'empoleon', name: 'Empoleon', region: 'sinnoh', dex: 395, types: ['Water', 'Steel'],
      hp: 94, atk: 101, def: 98, spd: 60,
      abilities: ['Torrent — when it is hurt, its water moves get stronger', 'Defiant — being pushed around makes it attack harder'],
      fact: 'The three horns on its beak show who is boss, and its wings can slice a floating ice sheet in two.',
      moves: [m('Bubble Beam', 'Water', 65), m('Metal Claw', 'Steel', 50), m('Flash Cannon', 'Steel', 80), m('Hydro Pump', 'Water', 110)],
      art: { shape: 'bird', body: '#3f7fc8', accent: '#f5d76e', belly: '#f0f8ff', beak: '#f5c040', wing: '#2f5f9f', ears: 'none', tail: 'fan', back: ['bigWings'], front: ['beak', 'crest'], eyes: 'angry', mouth: 'none' } },

    { id: 'luxray', name: 'Luxray', region: 'sinnoh', dex: 405, types: ['Electric'],
      hp: 90, atk: 120, def: 79, spd: 70,
      abilities: ['Rivalry — it fights harder against Pokemon of the same gender', 'Intimidate — it scares the other Pokemon into hitting softer'],
      fact: 'Its eyes can see straight through walls, so it always knows where you are hiding.',
      moves: [m('Spark', 'Electric', 65), m('Crunch', 'Dark', 80), m('Thunder Fang', 'Electric', 65), m('Wild Charge', 'Electric', 100)],
      art: { shape: 'quad', body: '#2f5ba8', accent: '#f7d02c', belly: '#4a78c8', mane: '#2a4a88', ears: 'point', earTip: '#f7d02c', tail: 'star', front: ['mane', 'fangsBig'], eyes: 'angry', mouth: 'none' } },

    { id: 'gible', name: 'Gible', region: 'sinnoh', dex: 443, types: ['Dragon', 'Ground'],
      hp: 68, atk: 70, def: 45, spd: 42,
      abilities: ['Sand Veil — it is hard to hit in a sandstorm', 'Rough Skin — attackers that touch it get scraped'],
      fact: 'It lives in warm caves and pounces on anything that walks past, biting first and thinking later.',
      moves: [m('Bite', 'Dark', 60), m('Dragon Claw', 'Dragon', 80), m('Dig', 'Ground', 80), m('Dragon Rush', 'Dragon', 100)],
      art: { shape: 'biped', body: '#4a8fc8', accent: '#e8553a', belly: '#f5f0e0', ears: 'none', tail: 'thin', front: ['jawTeeth'], eyes: 'happy', mouth: 'open' } },

    { id: 'garchomp', name: 'Garchomp', region: 'sinnoh', dex: 445, types: ['Dragon', 'Ground'],
      hp: 108, atk: 130, def: 95, spd: 102,
      abilities: ['Sand Veil — it is hard to hit in a sandstorm', 'Rough Skin — attackers that touch it get scraped'],
      fact: 'It folds its wings and flies as fast as a jet — pilots have mistaken it for an aircraft.',
      moves: [m('Dragon Claw', 'Dragon', 80), m('Earthquake', 'Ground', 100), m('Crunch', 'Dark', 80), m('Dragon Rush', 'Dragon', 110)],
      art: { shape: 'biped', body: '#3f7fb8', accent: '#e8553a', belly: '#f5f0e0', wing: '#3f7fb8', ears: 'point', earTip: '#2f5f98', tail: 'thin', back: ['bigWings'], front: ['fangsBig'], eyes: 'angry', mouth: 'fangs' } },

    { id: 'lucario', name: 'Lucario', region: 'sinnoh', dex: 448, types: ['Fighting', 'Steel'],
      hp: 90, atk: 115, def: 80, spd: 90,
      abilities: ['Steadfast — every time it flinches it gets faster', 'Inner Focus — it never flinches at all'],
      fact: 'It reads the aura that everything gives off, so it can tell how you feel from half a mile away.',
      moves: [m('Force Palm', 'Fighting', 60), m('Metal Claw', 'Steel', 50), m('Aura Sphere', 'Fighting', 80), m('Close Combat', 'Fighting', 100)],
      art: { shape: 'humanoid', body: '#3f6fc8', accent: '#2a2942', belly: '#f7d060', auraColor: '#8fd8ff', ears: 'point', earTip: '#2a2942', tail: 'bushy', front: ['mask'], back: ['aura'], eyes: 'angry', mouth: 'none' } },

    { id: 'leafeon', name: 'Leafeon', region: 'sinnoh', dex: 470, types: ['Grass'],
      hp: 65, atk: 110, def: 130, spd: 95,
      abilities: ['Leaf Guard — sunshine keeps it from getting sick', 'Chlorophyll — sunshine makes it super speedy'],
      fact: 'It does not eat — it makes its own food from sunlight, so it always smells like fresh grass.',
      moves: [m('Razor Leaf', 'Grass', 55), m('Quick Attack', 'Normal', 40), m('Leaf Blade', 'Grass', 90), m('Swords Dance', 'Normal', 40)],
      art: { shape: 'quad', body: '#e8f0c8', accent: '#7fc050', belly: '#f5f8e0', ears: 'leaf', earTip: '#7fc050', tail: 'leaf', front: ['headLeaf'], eyes: 'happy', mouth: 'smile' } },

    { id: 'glaceon', name: 'Glaceon', region: 'sinnoh', dex: 471, types: ['Ice'],
      hp: 65, atk: 130, def: 110, spd: 95,
      abilities: ['Snow Cloak — it is hard to hit in a snowstorm', 'Ice Body — a hailstorm slowly heals it'],
      fact: 'It can freeze the moisture in the air around it, and it lowers its own body heat to make ice crystals.',
      moves: [m('Ice Shard', 'Ice', 40), m('Bite', 'Dark', 60), m('Ice Beam', 'Ice', 90), m('Blizzard', 'Ice', 110)],
      art: { shape: 'quad', body: '#c8e8f5', accent: '#7fb8d8', belly: '#f0faff', ears: 'point', earTip: '#7fb8d8', tail: 'fan', front: ['headTuft'], eyes: 'sleepy', mouth: 'none' } },

    { id: 'dialga', name: 'Dialga', region: 'sinnoh', dex: 483, types: ['Steel', 'Dragon'], legend: true,
      hp: 130, atk: 140, def: 120, spd: 90,
      abilities: ['Pressure — the Pokemon facing it gets tired faster', 'Time Keeper — time itself flows because it exists'],
      fact: 'Time started moving when it was born, and it can stop or restart time whenever it likes.',
      moves: [m('Metal Claw', 'Steel', 50), m('Dragon Claw', 'Dragon', 80), m('Flash Cannon', 'Steel', 80), m('Roar of Time', 'Dragon', 120)],
      art: { shape: 'quad', body: '#5f8fd8', accent: '#8f8fa8', belly: '#c8d8f0', crownColor: '#7fd0f0', ears: 'point', earTip: '#8f8fa8', tail: 'thin', back: ['plates'], front: ['crown', 'gem'], eyes: 'angry', mouth: 'none' } },

    { id: 'palkia', name: 'Palkia', region: 'sinnoh', dex: 484, types: ['Water', 'Dragon'], legend: true,
      hp: 125, atk: 140, def: 110, spd: 100,
      abilities: ['Pressure — the Pokemon facing it gets tired faster', 'Space Keeper — space itself holds together because it exists'],
      fact: 'It lives in a gap between worlds and can fold space so two faraway places touch.',
      moves: [m('Water Pulse', 'Water', 60), m('Dragon Claw', 'Dragon', 80), m('Hydro Pump', 'Water', 110), m('Spacial Rend', 'Dragon', 120)],
      art: { shape: 'biped', body: '#e8e8f0', accent: '#e898c0', belly: '#f5f5fa', ears: 'point', earTip: '#e898c0', tail: 'thin', back: ['plates'], front: ['gem'], eyes: 'angry', mouth: 'none' } },

    { id: 'darkrai', name: 'Darkrai', region: 'sinnoh', dex: 491, types: ['Dark'], legend: true,
      hp: 110, atk: 135, def: 90, spd: 125,
      abilities: ['Bad Dreams — it feeds on the bad dreams of sleeping Pokemon', 'Night Cloak — it melts into shadows and vanishes'],
      fact: 'It does not mean to be scary — it puts people to sleep to protect itself, and it feels bad about the nightmares.',
      moves: [m('Feint Attack', 'Dark', 60), m('Shadow Ball', 'Ghost', 80), m('Dark Pulse', 'Dark', 80), m('Dark Void', 'Dark', 100)],
      art: { shape: 'ghost', body: '#2f2e42', accent: '#e8553a', belly: '#3f3e56', auraColor: '#6a5a8a', ears: 'tuft', earTip: '#f5f5fa', tail: 'none', back: ['aura'], eyes: 'angry', mouth: 'none' } }
  ]);
})();
