/* ===========================================================================
   dex-more-3.js — the rest of Unova, Kalos, Alola, Galar and Paldea
   =========================================================================== */
(function () {
  "use strict";
  const m = (name, type, power) => ({ name, type, power });

  window.DEX.add([
    /* ======================= UNOVA ======================= */
    { id: 'victini', name: 'Victini', region: 'unova', dex: 494, types: ['Psychic', 'Fire'], legend: true,
      hp: 100, atk: 100, def: 100, spd: 100,
      abilities: ['Victory Star — it makes itself and its friends aim better', 'Endless Energy — it creates limitless energy inside its body'],
      fact: 'Whoever it decides to help is said to win every battle they ever fight.',
      moves: [m('Quick Attack', 'Normal', 40), m('Zen Headbutt', 'Psychic', 80), m('Flame Charge', 'Fire', 50), m('V-create', 'Fire', 120)],
      art: { shape: 'biped', body: '#f7e07a', accent: '#e8553a', belly: '#fff6c8', ears: 'point', earTip: '#e8553a', tail: 'fan', front: ['bow'], back: ['sparkles'], eyes: 'happy', mouth: 'smile' } },

    { id: 'serperior', name: 'Serperior', region: 'unova', dex: 497, types: ['Grass'],
      hp: 95, atk: 85, def: 95, spd: 113,
      abilities: ['Overgrow — when it is hurt, its grass moves get stronger', 'Contrary — attacks meant to weaken it make it stronger instead'],
      fact: 'One look from it is enough to stop a fight — it only glares at opponents it thinks are worthy.',
      moves: [m('Leaf Blade', 'Grass', 90), m('Slam', 'Normal', 80), m('Energy Ball', 'Grass', 90), m('Leaf Storm', 'Grass', 110)],
      art: { shape: 'serpent', girth: 18, body: '#8ad08a', accent: '#5ca85c', belly: '#f5e0a8', ears: 'leaf', earTip: '#5ca85c', tail: 'leaf', front: ['crest'], eyes: 'angry', mouth: 'smirk' } },

    { id: 'emboar', name: 'Emboar', region: 'unova', dex: 500, types: ['Fire', 'Fighting'],
      hp: 110, atk: 123, def: 65, spd: 65,
      abilities: ['Blaze — when it is hurt, its fire moves get stronger', 'Reckless — moves that hurt it too are even stronger'],
      fact: 'It has a beard of fire, and it will happily take a hit to protect a friend.',
      moves: [m('Flame Charge', 'Fire', 50), m('Hammer Arm', 'Fighting', 100), m('Heat Crash', 'Fire', 90), m('Flare Blitz', 'Fire', 110)],
      art: { shape: 'humanoid', body: '#e8704a', accent: '#2a2942', belly: '#f5a86e', mane: '#f5b700', ears: 'point', earTip: '#2a2942', tail: 'curl', front: ['snout', 'mane'], eyes: 'angry', mouth: 'none' } },

    { id: 'samurott', name: 'Samurott', region: 'unova', dex: 503, types: ['Water'],
      hp: 95, atk: 100, def: 85, spd: 70,
      abilities: ['Torrent — when it is hurt, its water moves get stronger', 'Shell Armor — it can never be hit by a critical hit'],
      fact: 'One swing of the blades in its armour can fell an opponent — and it always bows first.',
      moves: [m('Razor Shell', 'Water', 75), m('Aqua Jet', 'Water', 60), m('Megahorn', 'Bug', 90), m('Hydro Pump', 'Water', 110)],
      art: { shape: 'quad', body: '#5f9ecf', accent: '#2a5c8a', belly: '#f0f8ff', mane: '#c8d8e8', ears: 'none', tail: 'fan', front: ['mane', 'whiskers'], eyes: 'angry', mouth: 'none' } },

    { id: 'zoroark', name: 'Zoroark', region: 'unova', dex: 571, types: ['Dark'],
      hp: 90, atk: 120, def: 70, spd: 105,
      abilities: ['Illusion — it looks exactly like another Pokemon until it gets hit', 'Trickster — it makes whole illusions to protect its family'],
      fact: 'It creates illusions of entire buildings to keep people away from the place it lives.',
      moves: [m('Feint Attack', 'Dark', 60), m('Night Slash', 'Dark', 75), m('Dark Pulse', 'Dark', 80), m('Night Daze', 'Dark', 95)],
      art: { shape: 'humanoid', body: '#4a4a66', accent: '#e8553a', belly: '#6a6a8a', mane: '#e8553a', ears: 'point', earTip: '#e8553a', tail: 'bushy', front: ['mane', 'mask'], eyes: 'angry', mouth: 'fangs' } },

    { id: 'haxorus', name: 'Haxorus', region: 'unova', dex: 612, types: ['Dragon'],
      hp: 96, atk: 137, def: 90, spd: 97,
      abilities: ['Rivalry — it fights harder against Pokemon of the same gender', 'Mold Breaker — the other Pokemon cannot use its ability to block'],
      fact: 'Its tusks can cut through steel girders and they never get blunt, no matter what it chews.',
      moves: [m('Dragon Claw', 'Dragon', 80), m('Dual Chop', 'Dragon', 50), m('Earthquake', 'Ground', 100), m('Outrage', 'Dragon', 120)],
      art: { shape: 'biped', body: '#f5c860', accent: '#c89840', belly: '#f0e0b0', ears: 'point', earTip: '#c89840', tail: 'thin', front: ['tusks'], back: ['plates'], eyes: 'angry', mouth: 'none' } },

    { id: 'reshiram', name: 'Reshiram', region: 'unova', dex: 643, types: ['Dragon', 'Fire'], legend: true,
      hp: 130, atk: 150, def: 100, spd: 90,
      abilities: ['Turboblaze — it attacks straight through any ability', 'Truth Seeker — it helps whoever is searching for the truth'],
      fact: 'When its tail burns, the weather over the whole world changes.',
      moves: [m('Dragon Breath', 'Dragon', 60), m('Fusion Flare', 'Fire', 100), m('Dragon Pulse', 'Dragon', 85), m('Blue Flare', 'Fire', 120)],
      art: { shape: 'biped', body: '#f7f7fa', accent: '#5f8fd8', belly: '#ffffff', wing: '#e8e8f0', ears: 'none', tail: 'flame', back: ['bigWings'], front: ['crest'], eyes: 'angry', mouth: 'none' } },

    { id: 'zekrom', name: 'Zekrom', region: 'unova', dex: 644, types: ['Dragon', 'Electric'], legend: true,
      hp: 130, atk: 150, def: 120, spd: 90,
      abilities: ['Teravolt — it attacks straight through any ability', 'Ideal Seeker — it helps whoever is chasing their ideals'],
      fact: 'Lightning crackles from the enormous generator in its tail, and thunderclouds follow it.',
      moves: [m('Dragon Breath', 'Dragon', 60), m('Fusion Bolt', 'Electric', 100), m('Dragon Claw', 'Dragon', 80), m('Bolt Strike', 'Electric', 120)],
      art: { shape: 'biped', body: '#2f2e42', accent: '#5f8fd8', belly: '#3f3e56', wing: '#4a4a66', ears: 'none', tail: 'star', back: ['bigWings'], front: ['crest'], eyes: 'angry', mouth: 'none' } },

    /* ======================= KALOS ======================= */
    { id: 'chesnaught', name: 'Chesnaught', region: 'kalos', dex: 652, types: ['Grass', 'Fighting'],
      hp: 108, atk: 107, def: 122, spd: 64,
      abilities: ['Overgrow — when it is hurt, its grass moves get stronger', 'Bulletproof — balls and bombs bounce right off it'],
      fact: 'It plants itself in front of its friends and takes the hit — its shell can stop a lorry.',
      moves: [m('Vine Whip', 'Grass', 45), m('Hammer Arm', 'Fighting', 100), m('Seed Bomb', 'Grass', 80), m('Wood Hammer', 'Grass', 110)],
      art: { shape: 'humanoid', body: '#7fa858', accent: '#8a5c3a', belly: '#e8e0c8', ears: 'none', tail: 'thin', back: ['spikes', 'plates'], eyes: 'angry', mouth: 'none' } },

    { id: 'delphox', name: 'Delphox', region: 'kalos', dex: 655, types: ['Fire', 'Psychic'],
      hp: 95, atk: 114, def: 80, spd: 104,
      abilities: ['Blaze — when it is hurt, its fire moves get stronger', 'Magician — it swipes the item of whoever it hits'],
      fact: 'It stares into a flame on the tip of its stick and sees things that have not happened yet.',
      moves: [m('Ember', 'Fire', 40), m('Psybeam', 'Psychic', 65), m('Flamethrower', 'Fire', 90), m('Mystical Fire', 'Fire', 75)],
      art: { shape: 'humanoid', body: '#f7c060', accent: '#e8553a', belly: '#fff6d8', mane: '#f5e0b0', ears: 'long', earTip: '#e8553a', tail: 'bushy', front: ['mane'], back: ['aura'], auraColor: '#f5b700', eyes: 'sleepy', mouth: 'none' } },

    { id: 'greninja', name: 'Greninja', region: 'kalos', dex: 658, types: ['Water', 'Dark'],
      hp: 92, atk: 113, def: 67, spd: 122,
      abilities: ['Torrent — when it is hurt, its water moves get stronger', 'Protean — it changes into the type of whatever move it uses'],
      fact: 'It makes throwing stars out of compressed water and vanishes before they land.',
      moves: [m('Water Shuriken', 'Water', 60), m('Night Slash', 'Dark', 75), m('Dark Pulse', 'Dark', 80), m('Hydro Pump', 'Water', 110)],
      art: { shape: 'humanoid', body: '#4a90c8', accent: '#e8553a', belly: '#f7f7fa', ears: 'none', tail: 'thin', front: ['mask'], eyes: 'angry', mouth: 'none' } },

    { id: 'pangoro', name: 'Pangoro', region: 'kalos', dex: 675, types: ['Fighting', 'Dark'],
      hp: 105, atk: 124, def: 78, spd: 58,
      abilities: ['Iron Fist — all its punching moves hit harder', 'Scrappy — it can even punch Ghost Pokemon'],
      fact: 'It looks like a bully but it will not stand for anyone picking on the little ones.',
      moves: [m('Arm Thrust', 'Fighting', 45), m('Crunch', 'Dark', 80), m('Hammer Arm', 'Fighting', 100), m('Body Slam', 'Normal', 85)],
      art: { shape: 'humanoid', body: '#d8d0c8', accent: '#4a4a66', belly: '#f5f0e8', ears: 'round', earTip: '#4a4a66', tail: 'none', front: ['mask', 'fangsBig'], eyes: 'angry', mouth: 'none' } },

    { id: 'xerneas', name: 'Xerneas', region: 'kalos', dex: 716, types: ['Fairy'], legend: true,
      hp: 126, atk: 131, def: 105, spd: 99,
      abilities: ['Fairy Aura — every fairy move on the field gets stronger', 'Life Giver — it can share eternal life'],
      fact: 'When the horns on its head shine in seven colours, it is giving life to everything nearby.',
      moves: [m('Fairy Wind', 'Fairy', 40), m('Moonblast', 'Fairy', 95), m('Dazzling Gleam', 'Fairy', 80), m('Geomancy', 'Fairy', 100)],
      art: { shape: 'quad', body: '#3f6fc8', accent: '#f7d02c', belly: '#7f9ed8', crownColor: '#f7d02c', ears: 'point', earTip: '#f7d02c', tail: 'bushy', front: ['crown'], back: ['aura'], auraColor: '#f7d02c', eyes: 'round', mouth: 'none' } },

    { id: 'yveltal', name: 'Yveltal', region: 'kalos', dex: 717, types: ['Dark', 'Flying'], legend: true,
      hp: 126, atk: 131, def: 105, spd: 99,
      abilities: ['Dark Aura — every dark move on the field gets stronger', 'Life Taker — it absorbs the life of everything around it'],
      fact: 'When its life ends it spreads its wings and takes the energy of everything nearby with it.',
      moves: [m('Dark Pulse', 'Dark', 80), m('Air Slash', 'Flying', 75), m('Oblivion Wing', 'Flying', 80), m('Hurricane', 'Flying', 110)],
      art: { shape: 'bird', body: '#c83f4a', accent: '#2f2e42', belly: '#8a2f3a', beak: '#2f2e42', wing: '#2f2e42', ears: 'none', tail: 'fan', back: ['bigWings'], front: ['beak', 'crest'], eyes: 'angry', mouth: 'none' } },

    { id: 'zygarde', name: 'Zygarde', region: 'kalos', dex: 718, types: ['Dragon', 'Ground'], legend: true,
      hp: 128, atk: 120, def: 121, spd: 95,
      abilities: ['Aura Break — it cancels out other auras', 'Order Keeper — it watches over the balance of the whole ecosystem'],
      fact: 'It is made of thousands of tiny cells that gather together when the world needs protecting.',
      moves: [m('Bulldoze', 'Ground', 60), m('Dragon Pulse', 'Dragon', 85), m('Earthquake', 'Ground', 100), m('Land\'s Wrath', 'Ground', 90)],
      art: { shape: 'serpent', girth: 20, body: '#2f6f5a', accent: '#e8553a', belly: '#5f9e7a', ears: 'fin', earTip: '#f7d02c', tail: 'none', front: ['crest', 'plates'], eyes: 'angry', mouth: 'none' } },

    /* ======================= ALOLA ======================= */
    { id: 'decidueye', name: 'Decidueye', region: 'alola', dex: 724, types: ['Grass', 'Ghost'],
      hp: 98, atk: 107, def: 80, spd: 70,
      abilities: ['Overgrow — when it is hurt, its grass moves get stronger', 'Long Reach — it attacks without ever touching the other Pokemon'],
      fact: 'It fires arrow-quills in a tenth of a second, and it hides its face when it is embarrassed.',
      moves: [m('Leafage', 'Grass', 40), m('Shadow Claw', 'Ghost', 70), m('Spirit Shackle', 'Ghost', 80), m('Leaf Blade', 'Grass', 90)],
      art: { shape: 'bird', body: '#8a6a48', accent: '#3f6f4a', belly: '#f5efe0', beak: '#f0a63a', wing: '#6a5438', ears: 'none', tail: 'fan', back: ['bigWings'], front: ['faceRing', 'beak', 'leafBow'], eyes: 'angry', mouth: 'none' } },

    { id: 'incineroar', name: 'Incineroar', region: 'alola', dex: 727, types: ['Fire', 'Dark'],
      hp: 95, atk: 115, def: 90, spd: 60,
      abilities: ['Blaze — when it is hurt, its fire moves get stronger', 'Intimidate — it scares the other Pokemon into hitting softer'],
      fact: 'It is a wrestling showman — it loves a crowd and it fires flames from the belt around its waist.',
      moves: [m('Fire Fang', 'Fire', 65), m('Darkest Lariat', 'Dark', 85), m('Flare Blitz', 'Fire', 110), m('Cross Chop', 'Fighting', 100)],
      art: { shape: 'humanoid', body: '#2f2e42', accent: '#e8553a', belly: '#f5a86e', ears: 'point', earTip: '#e8553a', tail: 'thin', front: ['stripes', 'fangsBig'], eyes: 'angry', mouth: 'none' } },

    { id: 'primarina', name: 'Primarina', region: 'alola', dex: 730, types: ['Water', 'Fairy'],
      hp: 100, atk: 116, def: 90, spd: 60,
      abilities: ['Torrent — when it is hurt, its water moves get stronger', 'Liquid Voice — its singing moves become water moves'],
      fact: 'It fights by singing — each note makes a water balloon it pops at exactly the right moment.',
      moves: [m('Bubble Beam', 'Water', 65), m('Disarming Voice', 'Fairy', 40), m('Moonblast', 'Fairy', 95), m('Sparkling Aria', 'Water', 90)],
      art: { shape: 'humanoid', body: '#7fc8e8', accent: '#f090b8', belly: '#ffffff', mane: '#a8dcf0', ears: 'none', tail: 'fan', front: ['mane', 'nose'], back: ['aura'], auraColor: '#f0a8d0', eyes: 'happy', mouth: 'open' } },

    { id: 'lycanroc', name: 'Lycanroc', region: 'alola', dex: 745, types: ['Rock'],
      hp: 85, atk: 115, def: 75, spd: 112,
      abilities: ['Keen Eye — its aim can never be lowered', 'Sand Rush — it doubles its speed in a sandstorm'],
      fact: 'It circles its opponent, then charges in low and fast — the rocks in its mane are razor sharp.',
      moves: [m('Rock Throw', 'Rock', 50), m('Crunch', 'Dark', 80), m('Rock Slide', 'Rock', 75), m('Stone Edge', 'Rock', 100)],
      art: { shape: 'quad', body: '#c8a878', accent: '#8a6848', belly: '#f0e0c8', mane: '#f5f0e0', ears: 'point', earTip: '#8a6848', tail: 'bushy', front: ['mane', 'collarRocks'], eyes: 'angry', mouth: 'none' } },

    { id: 'tapukoko', name: 'Tapu Koko', region: 'alola', dex: 785, types: ['Electric', 'Fairy'], legend: true,
      hp: 105, atk: 125, def: 90, spd: 130,
      abilities: ['Electric Surge — the whole field crackles with electricity', 'Island Guardian — it protects the island it belongs to'],
      fact: 'It is the guardian of Melemele Island — curious about people, and quick to lose its temper.',
      moves: [m('Thunder Shock', 'Electric', 40), m('Dazzling Gleam', 'Fairy', 80), m('Thunderbolt', 'Electric', 90), m('Nature\'s Madness', 'Fairy', 90)],
      art: { shape: 'humanoid', body: '#f7d02c', accent: '#2f2e42', belly: '#fff0a0', ears: 'none', tail: 'none', front: ['mask', 'crown'], crownColor: '#e8553a', back: ['aura'], auraColor: '#f7d02c', eyes: 'angry', mouth: 'none' } },

    { id: 'solgaleo', name: 'Solgaleo', region: 'alola', dex: 791, types: ['Psychic', 'Steel'], legend: true,
      hp: 137, atk: 137, def: 107, spd: 97,
      abilities: ['Full Metal Body — nothing can lower its stats', 'Sunsteel — it can open doorways to other worlds'],
      fact: 'It is called the beast that devours the sun, and its mane blazes when it is ready to fight.',
      moves: [m('Metal Claw', 'Steel', 50), m('Zen Headbutt', 'Psychic', 80), m('Flash Cannon', 'Steel', 80), m('Sunsteel Strike', 'Steel', 120)],
      art: { shape: 'quad', body: '#f7f7fa', accent: '#f5b700', belly: '#f0f0f5', mane: '#f7d02c', ears: 'point', earTip: '#f5b700', tail: 'bushy', front: ['mane', 'fangsBig'], back: ['aura'], auraColor: '#f7d02c', eyes: 'angry', mouth: 'none' } },

    { id: 'lunala', name: 'Lunala', region: 'alola', dex: 792, types: ['Psychic', 'Ghost'], legend: true,
      hp: 137, atk: 137, def: 107, spd: 97,
      abilities: ['Shadow Shield — at full health, everything hurts it half as much', 'Moonshadow — it can open doorways to other worlds'],
      fact: 'It is called the beast that calls the moon, and it turns into a crescent when it sleeps.',
      moves: [m('Confusion', 'Psychic', 50), m('Shadow Ball', 'Ghost', 80), m('Moongeist Beam', 'Ghost', 100), m('Psychic', 'Psychic', 100)],
      art: { shape: 'bird', body: '#3f3e6a', accent: '#7fd0f0', belly: '#5f5e8a', beak: '#7fd0f0', wing: '#2f2e52', ears: 'none', tail: 'fan', back: ['bigWings'], front: ['beak', 'crest'], eyes: 'angry', mouth: 'none' } },

    /* ======================= GALAR ======================= */
    { id: 'rillaboom', name: 'Rillaboom', region: 'galar', dex: 812, types: ['Grass'],
      hp: 100, atk: 125, def: 90, spd: 85,
      abilities: ['Overgrow — when it is hurt, its grass moves get stronger', 'Grassy Surge — it turns the whole field into soft healing grass'],
      fact: 'It drums on the tree stump it carries everywhere — the rhythm makes roots burst out of the ground.',
      moves: [m('Branch Poke', 'Grass', 40), m('Drum Beating', 'Grass', 80), m('Wood Hammer', 'Grass', 110), m('Body Slam', 'Normal', 85)],
      art: { shape: 'humanoid', body: '#5ca85c', accent: '#c9a878', belly: '#8ad08a', mane: '#3f7f3f', ears: 'round', earTip: '#c9a878', tail: 'curl', front: ['mane'], eyes: 'angry', mouth: 'none' } },

    { id: 'cinderace', name: 'Cinderace', region: 'galar', dex: 815, types: ['Fire'],
      hp: 90, atk: 116, def: 75, spd: 119,
      abilities: ['Blaze — when it is hurt, its fire moves get stronger', 'Libero — it changes into the type of whatever move it uses'],
      fact: 'It kicks a flaming ball of pebbles like a striker, and it never misses the goal.',
      moves: [m('Quick Attack', 'Normal', 40), m('Flame Charge', 'Fire', 50), m('Pyro Ball', 'Fire', 100), m('High Jump Kick', 'Fighting', 110)],
      art: { shape: 'humanoid', body: '#f7f7fa', accent: '#e8553a', belly: '#ffffff', cheek: '#ef6b63', ears: 'long', earTip: '#e8553a', tail: 'bushy', front: ['nose'], eyes: 'smirk', mouth: 'smirk' } },

    { id: 'inteleon', name: 'Inteleon', region: 'galar', dex: 818, types: ['Water'],
      hp: 90, atk: 112, def: 70, spd: 120,
      abilities: ['Torrent — when it is hurt, its water moves get stronger', 'Sniper — its critical hits do even more damage'],
      fact: 'It fires water from its fingertip with sniper accuracy from nearly a mile away.',
      moves: [m('Water Gun', 'Water', 40), m('Snipe Shot', 'Water', 80), m('Liquidation', 'Water', 85), m('Hydro Pump', 'Water', 110)],
      art: { shape: 'humanoid', body: '#5fa8d8', accent: '#2f6f9f', belly: '#f7f7fa', ears: 'none', tail: 'thin', front: ['mask'], eyes: 'smirk', mouth: 'smirk' } },

    { id: 'corviknight', name: 'Corviknight', region: 'galar', dex: 823, types: ['Flying', 'Steel'],
      hp: 98, atk: 87, def: 105, spd: 67,
      abilities: ['Pressure — the Pokemon facing it gets tired faster', 'Mirror Armor — anything that lowers its stats gets reflected back'],
      fact: 'It rules the sky over Galar, and people pay it to carry them around in flying taxis.',
      moves: [m('Peck', 'Flying', 35), m('Steel Wing', 'Steel', 70), m('Drill Peck', 'Flying', 80), m('Iron Head', 'Steel', 80)],
      art: { shape: 'bird', body: '#3f3e52', accent: '#8f8fa8', belly: '#4f4e66', beak: '#8f8fa8', wing: '#2f2e42', ears: 'none', tail: 'fan', back: ['bigWings'], front: ['beak', 'crest'], eyes: 'angry', mouth: 'none' } },

    { id: 'dubwool', name: 'Dubwool', region: 'galar', dex: 832, types: ['Normal'],
      hp: 92, atk: 80, def: 100, spd: 88,
      abilities: ['Fluffy — hits hurt half as much, but fire hurts double', 'Bulletproof — balls and bombs bounce right off it'],
      fact: 'Its fleece is springy enough that a rug made from it bounces you back up if you fall.',
      moves: [m('Headbutt', 'Normal', 70), m('Double Kick', 'Fighting', 60), m('Body Slam', 'Normal', 85), m('Double-Edge', 'Normal', 100)],
      art: { shape: 'blob', body: '#2a2942', accent: '#2a2942', belly: '#f7f2e4', ears: 'round', earTip: '#3a3852', tail: 'none', back: ['fluff'], front: ['hooves', 'hornPair'], eyes: 'happy', mouth: 'smile' } },

    { id: 'dreepy', name: 'Dreepy', region: 'galar', dex: 885, types: ['Dragon', 'Ghost'],
      hp: 60, atk: 50, def: 40, spd: 82,
      abilities: ['Clear Body — nothing can lower its stats', 'Infiltrator — barriers cannot keep it out'],
      fact: 'It is the ghost of a Pokemon from long ago — if its friends cheer it on, it trains to get strong again.',
      moves: [m('Astonish', 'Ghost', 30), m('Bite', 'Dark', 60), m('Dragon Breath', 'Dragon', 60), m('Shadow Ball', 'Ghost', 80)],
      art: { shape: 'ghost', body: '#8fd0c8', accent: '#e8607a', belly: '#b0e0d8', ears: 'fin', earTip: '#e8607a', tail: 'none', eyes: 'sleepy', mouth: 'none' } },

    { id: 'dragapult', name: 'Dragapult', region: 'galar', dex: 887, types: ['Dragon', 'Ghost'],
      hp: 93, atk: 120, def: 75, spd: 142,
      abilities: ['Clear Body — nothing can lower its stats', 'Cursed Body — the move that hits it might break'],
      fact: 'It keeps two Dreepy in the horns on its head and fires them out at supersonic speed — and they love it.',
      moves: [m('Dragon Breath', 'Dragon', 60), m('Shadow Ball', 'Ghost', 80), m('Dragon Darts', 'Dragon', 100), m('Phantom Force', 'Ghost', 90)],
      art: { shape: 'biped', body: '#3f8f8a', accent: '#e8607a', belly: '#8fd0c8', wing: '#5fa8a0', ears: 'fin', earTip: '#e8607a', tail: 'thin', back: ['bigWings'], front: ['hornPair'], eyes: 'angry', mouth: 'none' } },

    { id: 'zacian', name: 'Zacian', region: 'galar', dex: 888, types: ['Fairy', 'Steel'], legend: true,
      hp: 122, atk: 150, def: 115, spd: 138,
      abilities: ['Intrepid Sword — it draws its sword and its attack shoots up', 'Hero of Many Battles — it has fought for Galar for centuries'],
      fact: 'It holds a giant sword in its mouth and can cut through anything in a single flash.',
      moves: [m('Metal Claw', 'Steel', 50), m('Play Rough', 'Fairy', 70), m('Sacred Sword', 'Fighting', 90), m('Behemoth Blade', 'Steel', 120)],
      art: { shape: 'quad', body: '#7fc8e8', accent: '#f5b700', belly: '#c8e8f5', mane: '#5f9ecf', crownColor: '#f5b700', ears: 'point', earTip: '#f5b700', tail: 'bushy', front: ['mane', 'crown'], back: ['aura'], auraColor: '#7fd0f0', eyes: 'angry', mouth: 'none' } },

    { id: 'zamazenta', name: 'Zamazenta', region: 'galar', dex: 889, types: ['Fighting', 'Steel'], legend: true,
      hp: 122, atk: 130, def: 145, spd: 128,
      abilities: ['Dauntless Shield — it raises its shield and its defence shoots up', 'Hero of Many Battles — it has fought for Galar for centuries'],
      fact: 'Its shield-like mane can turn away any attack, and it fought beside Zacian to save Galar.',
      moves: [m('Metal Claw', 'Steel', 50), m('Crunch', 'Dark', 80), m('Sacred Sword', 'Fighting', 90), m('Behemoth Bash', 'Steel', 120)],
      art: { shape: 'quad', body: '#e8607a', accent: '#f5b700', belly: '#f5a8b8', mane: '#c83f5a', crownColor: '#f5b700', ears: 'point', earTip: '#f5b700', tail: 'bushy', front: ['mane', 'crown'], back: ['aura'], auraColor: '#f0a8b8', eyes: 'angry', mouth: 'none' } },

    /* ======================= PALDEA ======================= */
    { id: 'meowscarada', name: 'Meowscarada', region: 'paldea', dex: 908, types: ['Grass', 'Dark'],
      hp: 96, atk: 110, def: 70, spd: 123,
      abilities: ['Overgrow — when it is hurt, its grass moves get stronger', 'Protean — it changes into the type of whatever move it uses'],
      fact: 'It makes a flower out of leaves, throws it as a decoy, and strikes while you are watching the flower.',
      moves: [m('Leafage', 'Grass', 40), m('Night Slash', 'Dark', 75), m('Flower Trick', 'Grass', 90), m('Play Rough', 'Fairy', 70)],
      art: { shape: 'humanoid', body: '#5ca85c', accent: '#e8607a', belly: '#8ad08a', ears: 'point', earTip: '#e8607a', tail: 'leaf', front: ['mask', 'whiskers'], eyes: 'smirk', mouth: 'smirk' } },

    { id: 'skeledirge', name: 'Skeledirge', region: 'paldea', dex: 911, types: ['Fire', 'Ghost'],
      hp: 114, atk: 110, def: 100, spd: 66,
      abilities: ['Blaze — when it is hurt, its fire moves get stronger', 'Unaware — it is too laid back to notice stat changes'],
      fact: 'The little fire bird on its head sings, and the song makes its flames roar higher.',
      moves: [m('Ember', 'Fire', 40), m('Shadow Ball', 'Ghost', 80), m('Torch Song', 'Fire', 80), m('Flamethrower', 'Fire', 90)],
      art: { shape: 'quad', body: '#c83f4a', accent: '#f5c060', belly: '#e8704a', ears: 'none', tail: 'thin', back: ['backFlames'], front: ['jawTeeth'], eyes: 'sleepy', mouth: 'open' } },

    { id: 'quaquaval', name: 'Quaquaval', region: 'paldea', dex: 914, types: ['Water', 'Fighting'],
      hp: 105, atk: 120, def: 80, spd: 85,
      abilities: ['Torrent — when it is hurt, its water moves get stronger', 'Moxie — every time it wins it gets stronger'],
      fact: 'It dances a carnival dance, and every kick in the routine is a real attack.',
      moves: [m('Wing Attack', 'Flying', 60), m('Aqua Step', 'Water', 80), m('Aqua Cutter', 'Water', 70), m('Close Combat', 'Fighting', 100)],
      art: { shape: 'bird', body: '#3f7fc8', accent: '#e8553a', belly: '#f7f7fa', beak: '#f0c040', wing: '#f5b700', ears: 'none', tail: 'fan', back: ['bigWings'], front: ['beak', 'quiff'], eyes: 'smirk', mouth: 'none' } },

    { id: 'pawmot', name: 'Pawmot', region: 'paldea', dex: 923, types: ['Electric', 'Fighting'],
      hp: 90, atk: 115, def: 70, spd: 105,
      abilities: ['Volt Absorb — electric attacks heal it instead of hurting', 'Iron Fist — all its punching moves hit harder'],
      fact: 'It stores so much electricity in its fur that it can jump-start the heart of a fainted Pokemon.',
      moves: [m('Spark', 'Electric', 65), m('Mach Punch', 'Fighting', 40), m('Thunder Punch', 'Electric', 75), m('Close Combat', 'Fighting', 100)],
      art: { shape: 'humanoid', body: '#f7d060', accent: '#e8553a', belly: '#fff6d8', cheek: '#ef6b63', mane: '#f5e0b0', ears: 'round', earTip: '#e8a060', tail: 'thin', front: ['cheeks', 'mane'], eyes: 'angry', mouth: 'none' } },

    { id: 'tinkaton', name: 'Tinkaton', region: 'paldea', dex: 959, types: ['Fairy', 'Steel'],
      hp: 95, atk: 105, def: 87, spd: 94,
      abilities: ['Mold Breaker — the other Pokemon cannot use its ability to block', 'Pickpocket — it steals the item of whoever touches it'],
      fact: 'It swings a hammer heavier than itself, and it collects Corviknight feathers as trophies.',
      moves: [m('Fairy Wind', 'Fairy', 40), m('Metal Claw', 'Steel', 50), m('Play Rough', 'Fairy', 70), m('Gigaton Hammer', 'Steel', 120)],
      art: { shape: 'humanoid', body: '#f7b8d8', accent: '#8f8fa8', belly: '#ffffff', cheek: '#ef6b63', ears: 'point', earTip: '#8f8fa8', tail: 'thin', front: ['bow', 'crown'], crownColor: '#8f8fa8', eyes: 'smirk', mouth: 'smirk' } },

    { id: 'koraidon', name: 'Koraidon', region: 'paldea', dex: 1007, types: ['Fighting', 'Dragon'], legend: true,
      hp: 130, atk: 135, def: 115, spd: 135,
      abilities: ['Orichalcum Pulse — sunshine blazes and its attack climbs', 'Ancient Ride — it can run, swim, glide and climb anywhere'],
      fact: 'It came from the distant past, and it will carry you across mountains, seas and skies.',
      moves: [m('Dragon Claw', 'Dragon', 80), m('Flame Charge', 'Fire', 50), m('Close Combat', 'Fighting', 100), m('Collision Course', 'Fighting', 120)],
      art: { shape: 'biped', body: '#e8553a', accent: '#f7f7fa', belly: '#f5a86e', mane: '#f5f0e0', crownColor: '#f5f0e0', ears: 'point', earTip: '#f7f7fa', tail: 'thin', front: ['mane', 'crown', 'fangsBig'], eyes: 'angry', mouth: 'none' } },

    { id: 'miraidon', name: 'Miraidon', region: 'paldea', dex: 1008, types: ['Electric', 'Dragon'], legend: true,
      hp: 130, atk: 135, def: 115, spd: 135,
      abilities: ['Hadron Engine — the field electrifies and its power climbs', 'Future Ride — it changes shape into a bike, a boat or a glider'],
      fact: 'It came from the far future, and nobody is quite sure whether it is a Pokemon or a machine.',
      moves: [m('Dragon Claw', 'Dragon', 80), m('Thunder Fang', 'Electric', 65), m('Thunderbolt', 'Electric', 90), m('Electro Drift', 'Electric', 120)],
      art: { shape: 'biped', body: '#3f6fc8', accent: '#7fd0f0', belly: '#7f9ed8', mane: '#c8e8f5', crownColor: '#7fd0f0', ears: 'point', earTip: '#7fd0f0', tail: 'star', front: ['mane', 'crown', 'fangsBig'], eyes: 'angry', mouth: 'none' } }
  ]);
})();
