/* ===========================================================================
   dex-more-1.js — the rest of Kanto, plus every evolution chain in the game
   =========================================================================== */
(function () {
  "use strict";
  const m = (name, type, power) => ({ name, type, power });

  window.DEX.add([
    /* ---------------- starter lines ---------------- */
    { id: 'ivysaur', name: 'Ivysaur', region: 'kanto', dex: 2, types: ['Grass', 'Poison'],
      hp: 75, atk: 65, def: 68, spd: 60,
      abilities: ['Overgrow — when it is hurt, its grass moves get stronger', 'Chlorophyll — sunshine makes it super speedy'],
      fact: 'The bud on its back is getting heavy, so its legs grew thick and strong.',
      moves: [m('Vine Whip', 'Grass', 45), m('Razor Leaf', 'Grass', 55), m('Sludge Bomb', 'Poison', 80), m('Take Down', 'Normal', 85)],
      art: { shape: 'quad', body: '#7fc8a8', accent: '#5fae8c', belly: '#cdf0da', ears: 'none', tail: 'none', back: ['bulb'], front: ['spots'], eyes: 'round', mouth: 'smile' } },

    { id: 'venusaur', name: 'Venusaur', region: 'kanto', dex: 3, types: ['Grass', 'Poison'],
      hp: 95, atk: 82, def: 83, spd: 80,
      abilities: ['Overgrow — when it is hurt, its grass moves get stronger', 'Thick Fat — fire and ice attacks hurt it only half as much'],
      fact: 'The flower on its back releases a smell so sweet it soothes anyone who fights it.',
      moves: [m('Razor Leaf', 'Grass', 55), m('Sludge Bomb', 'Poison', 80), m('Earthquake', 'Ground', 95), m('Solar Beam', 'Grass', 110)],
      art: { shape: 'quad', body: '#6fb894', accent: '#f090b8', belly: '#cdf0da', ears: 'none', tail: 'none', back: ['bulb'], front: ['spots', 'fangsBig'], eyes: 'angry', mouth: 'none' } },

    { id: 'charmeleon', name: 'Charmeleon', region: 'kanto', dex: 5, types: ['Fire'],
      hp: 73, atk: 80, def: 58, spd: 80,
      abilities: ['Blaze — when it is hurt, its fire moves get stronger', 'Solar Power — sunshine makes its attacks fiercer'],
      fact: 'It gets mean when it is winning, and its tail flame burns blue-white when it rages.',
      moves: [m('Ember', 'Fire', 40), m('Slash', 'Normal', 70), m('Dragon Breath', 'Dragon', 60), m('Flamethrower', 'Fire', 85)],
      art: { shape: 'biped', body: '#e8553a', accent: '#c43f2a', belly: '#ffd6a0', ears: 'point', earTip: '#c43f2a', tail: 'flame', eyes: 'angry', mouth: 'fangs' } },

    { id: 'charizard', name: 'Charizard', region: 'kanto', dex: 6, types: ['Fire', 'Flying'],
      hp: 98, atk: 104, def: 78, spd: 100,
      abilities: ['Blaze — when it is hurt, its fire moves get stronger', 'Tough Claws — moves where it touches you hit harder'],
      fact: 'Its fire is hot enough to melt boulders, and it flies high enough to see the whole sky.',
      moves: [m('Wing Attack', 'Flying', 60), m('Dragon Claw', 'Dragon', 80), m('Air Slash', 'Flying', 75), m('Flamethrower', 'Fire', 90)],
      art: { shape: 'biped', body: '#f0863a', accent: '#d06a25', belly: '#f5d0a0', wing: '#3f8fa8', ears: 'point', earTip: '#d06a25', tail: 'flame', back: ['bigWings'], eyes: 'angry', mouth: 'fangs' } },

    { id: 'wartortle', name: 'Wartortle', region: 'kanto', dex: 8, types: ['Water'],
      hp: 79, atk: 63, def: 80, spd: 58,
      abilities: ['Torrent — when it is hurt, its water moves get stronger', 'Rain Dish — rain slowly heals it'],
      fact: 'Its furry ears and tail are said to be a sign of a very long life.',
      moves: [m('Water Gun', 'Water', 40), m('Bite', 'Dark', 60), m('Aqua Tail', 'Water', 80), m('Ice Beam', 'Ice', 85)],
      art: { shape: 'biped', body: '#7fb8d8', accent: '#5f98b8', belly: '#f7e9b0', shell: '#9a6a2f', shell2: '#d09a55', ears: 'fin', earTip: '#f5f0e0', tail: 'bushy', back: ['shell'], eyes: 'round', mouth: 'smile' } },

    { id: 'blastoise', name: 'Blastoise', region: 'kanto', dex: 9, types: ['Water'],
      hp: 99, atk: 83, def: 100, spd: 78,
      abilities: ['Torrent — when it is hurt, its water moves get stronger', 'Rain Dish — rain slowly heals it'],
      fact: 'The water cannons in its shell can punch through steel from a long way off.',
      moves: [m('Water Pulse', 'Water', 60), m('Bite', 'Dark', 60), m('Ice Beam', 'Ice', 85), m('Hydro Pump', 'Water', 110)],
      art: { shape: 'biped', body: '#6a9ed8', accent: '#4a7eb8', belly: '#f7e9b0', shell: '#8a5a2f', shell2: '#c08a4a', ears: 'none', tail: 'thin', back: ['shell'], front: ['jawTeeth'], eyes: 'angry', mouth: 'none' } },

    /* ---------------- famous Kanto ---------------- */
    { id: 'pidgey', name: 'Pidgey', region: 'kanto', dex: 16, types: ['Normal', 'Flying'],
      hp: 60, atk: 45, def: 40, spd: 56,
      abilities: ['Keen Eye — its aim can never be lowered', 'Big Pecks — its defence can never be lowered'],
      fact: 'It flaps up a cloud of sand to hide in — it hates fighting if it can help it.',
      moves: [m('Tackle', 'Normal', 40), m('Gust', 'Flying', 40), m('Quick Attack', 'Normal', 40), m('Wing Attack', 'Flying', 60)],
      art: { shape: 'bird', body: '#c8a878', accent: '#8a6a48', belly: '#f5e7c8', beak: '#f0a63a', ears: 'none', tail: 'fan', front: ['beak', 'crest'], eyes: 'round', mouth: 'none' } },

    { id: 'pidgeot', name: 'Pidgeot', region: 'kanto', dex: 18, types: ['Normal', 'Flying'],
      hp: 93, atk: 80, def: 75, spd: 101,
      abilities: ['Keen Eye — its aim can never be lowered', 'No Guard — every attack hits, both ways'],
      fact: 'It flies at nearly the speed of sound, and its crest is beautiful enough to stop a crowd.',
      moves: [m('Wing Attack', 'Flying', 60), m('Quick Attack', 'Normal', 40), m('Air Slash', 'Flying', 75), m('Hurricane', 'Flying', 100)],
      art: { shape: 'bird', body: '#c8a060', accent: '#8a5a30', belly: '#f5e7c8', beak: '#f0a63a', wing: '#a87d45', ears: 'none', tail: 'fan', back: ['bigWings'], front: ['beak', 'crest'], eyes: 'angry', mouth: 'none' } },

    { id: 'raichu', name: 'Raichu', region: 'kanto', dex: 26, types: ['Electric'],
      hp: 80, atk: 90, def: 55, spd: 110,
      abilities: ['Static — anyone who touches it might get zapped', 'Lightning Rod — it soaks up electric attacks instead of being hurt'],
      fact: 'It sticks its tail in the ground to earth itself before firing off a huge zap.',
      moves: [m('Thunder Shock', 'Electric', 40), m('Quick Attack', 'Normal', 40), m('Iron Tail', 'Steel', 75), m('Thunder', 'Electric', 100)],
      art: { shape: 'biped', body: '#f0a83a', accent: '#c88020', belly: '#fff0c8', cheek: '#f5b700', ears: 'long', earTip: '#2b2b3a', tail: 'star', front: ['cheeks'], eyes: 'round', mouth: 'w' } },

    { id: 'vulpix', name: 'Vulpix', region: 'kanto', dex: 37, types: ['Fire'],
      hp: 58, atk: 50, def: 48, spd: 65,
      abilities: ['Flash Fire — fire attacks make it stronger, not weaker', 'Drought — it makes the sun blaze the moment it appears'],
      fact: 'It is born with one white tail that splits into six as it grows.',
      moves: [m('Ember', 'Fire', 40), m('Quick Attack', 'Normal', 40), m('Flame Charge', 'Fire', 50), m('Flamethrower', 'Fire', 85)],
      art: { shape: 'quad', body: '#e8845c', accent: '#c86a45', belly: '#f5d0b0', ears: 'point', earTip: '#c86a45', tail: 'bushy', front: ['headTuft'], eyes: 'sparkle', mouth: 'smile' } },

    { id: 'ninetales', name: 'Ninetales', region: 'kanto', dex: 38, types: ['Fire'],
      hp: 88, atk: 76, def: 75, spd: 100,
      abilities: ['Flash Fire — fire attacks make it stronger, not weaker', 'Drought — it makes the sun blaze the moment it appears'],
      fact: 'Legend says each of its nine tails holds a magic power, and it can live a thousand years.',
      moves: [m('Ember', 'Fire', 40), m('Extrasensory', 'Psychic', 80), m('Flamethrower', 'Fire', 90), m('Fire Blast', 'Fire', 110)],
      art: { shape: 'quad', body: '#f5e8c8', accent: '#e0c890', belly: '#fffaf0', mane: '#f0d8a0', ears: 'point', earTip: '#e0c890', tail: 'bushy', front: ['mane'], eyes: 'angry', mouth: 'none' } },

    { id: 'meowth', name: 'Meowth', region: 'kanto', dex: 52, types: ['Normal'],
      hp: 60, atk: 55, def: 40, spd: 90,
      abilities: ['Pickup — it finds items other Pokemon drop', 'Technician — its weaker moves hit surprisingly hard'],
      fact: 'It loves round shiny things and collects coins it finds while wandering at night.',
      moves: [m('Scratch', 'Normal', 40), m('Bite', 'Dark', 60), m('Fury Swipes', 'Normal', 55), m('Slash', 'Normal', 70)],
      art: { shape: 'quad', body: '#f5e0b0', accent: '#d8c090', belly: '#fff8e0', cheek: '#f5b700', ears: 'point', earTip: '#c8a878', tail: 'curl', front: ['whiskers', 'gem'], eyes: 'smirk', mouth: 'smirk' } },

    { id: 'psyduck', name: 'Psyduck', region: 'kanto', dex: 54, types: ['Water'],
      hp: 70, atk: 62, def: 48, spd: 55,
      abilities: ['Cloud Nine — it ignores the weather completely', 'Damp — it soaks the ground so explosions cannot happen'],
      fact: 'It always has a headache, and when the headache is bad enough its psychic powers burst out.',
      moves: [m('Water Gun', 'Water', 40), m('Confusion', 'Psychic', 50), m('Water Pulse', 'Water', 60), m('Psychic', 'Psychic', 90)],
      art: { shape: 'bird', body: '#f5d76e', accent: '#e0be50', belly: '#fff0b8', beak: '#f0b840', ears: 'none', tail: 'none', front: ['beak', 'headTuft'], eyes: 'round', mouth: 'none' } },

    { id: 'growlithe', name: 'Growlithe', region: 'kanto', dex: 58, types: ['Fire'],
      hp: 63, atk: 70, def: 45, spd: 60,
      abilities: ['Intimidate — it scares the other Pokemon into hitting softer', 'Flash Fire — fire attacks make it stronger, not weaker'],
      fact: 'It is fiercely loyal and will bark and bite at anything bigger than itself to protect you.',
      moves: [m('Bite', 'Dark', 60), m('Ember', 'Fire', 40), m('Flame Wheel', 'Fire', 60), m('Flamethrower', 'Fire', 85)],
      art: { shape: 'quad', body: '#f0863a', accent: '#2a2942', belly: '#f5e0c0', mane: '#f5e8c8', ears: 'point', earTip: '#d06a25', tail: 'bushy', front: ['mane', 'stripes'], eyes: 'round', mouth: 'open' } },

    { id: 'arcanine', name: 'Arcanine', region: 'kanto', dex: 59, types: ['Fire'],
      hp: 105, atk: 110, def: 80, spd: 95,
      abilities: ['Intimidate — it scares the other Pokemon into hitting softer', 'Justified — being hit by a dark move makes it stronger'],
      fact: 'It can run 6,000 miles in a single day and night — people call it the legendary Pokemon.',
      moves: [m('Bite', 'Dark', 60), m('Flame Wheel', 'Fire', 60), m('Crunch', 'Dark', 80), m('Flare Blitz', 'Fire', 110)],
      art: { shape: 'quad', body: '#f0863a', accent: '#2a2942', belly: '#f5e8c8', mane: '#f5e8c8', ears: 'point', earTip: '#d06a25', tail: 'bushy', front: ['mane', 'stripes', 'fangsBig'], eyes: 'angry', mouth: 'none' } },

    { id: 'machop', name: 'Machop', region: 'kanto', dex: 66, types: ['Fighting'],
      hp: 70, atk: 80, def: 50, spd: 35,
      abilities: ['Guts — feeling poorly makes it punch harder', 'No Guard — every attack hits, both ways'],
      fact: 'It trains by lifting grown Graveler, and it can throw a hundred adults over its shoulder.',
      moves: [m('Karate Chop', 'Fighting', 55), m('Low Kick', 'Fighting', 60), m('Seismic Toss', 'Fighting', 70), m('Cross Chop', 'Fighting', 100)],
      art: { shape: 'humanoid', body: '#9ab8c8', accent: '#7a98a8', belly: '#d8e8f0', ears: 'none', tail: 'thin', eyes: 'angry', mouth: 'none' } },

    { id: 'machamp', name: 'Machamp', region: 'kanto', dex: 68, types: ['Fighting'],
      hp: 100, atk: 120, def: 70, spd: 55,
      abilities: ['Guts — feeling poorly makes it punch harder', 'No Guard — every attack hits, both ways'],
      fact: 'It has four arms, so it can throw two hundred punches in only two seconds.',
      moves: [m('Karate Chop', 'Fighting', 55), m('Rock Slide', 'Rock', 75), m('Cross Chop', 'Fighting', 100), m('Dynamic Punch', 'Fighting', 100)],
      art: { shape: 'humanoid', body: '#7fa8c8', accent: '#5f88a8', belly: '#e8e0d0', ears: 'none', tail: 'none', front: ['fangsBig'], eyes: 'angry', mouth: 'none' } },

    { id: 'abra', name: 'Abra', region: 'kanto', dex: 63, types: ['Psychic'],
      hp: 55, atk: 45, def: 30, spd: 90,
      abilities: ['Inner Focus — it never flinches', 'Magic Guard — only direct attacks can ever hurt it'],
      fact: 'It sleeps eighteen hours a day and teleports away in its sleep if it senses danger.',
      moves: [m('Confusion', 'Psychic', 50), m('Psybeam', 'Psychic', 65), m('Psyshock', 'Psychic', 80), m('Psychic', 'Psychic', 90)],
      art: { shape: 'humanoid', body: '#f7c860', accent: '#8a6a48', belly: '#f0d8a0', ears: 'point', earTip: '#8a6a48', tail: 'thin', eyes: 'sleepy', mouth: 'none' } },

    { id: 'alakazam', name: 'Alakazam', region: 'kanto', dex: 65, types: ['Psychic'],
      hp: 80, atk: 95, def: 45, spd: 120,
      abilities: ['Synchronize — whatever bad thing happens to it happens to the attacker too', 'Magic Guard — only direct attacks can ever hurt it'],
      fact: 'Its brain never stops growing, and it remembers absolutely everything that has ever happened to it.',
      moves: [m('Confusion', 'Psychic', 50), m('Shadow Ball', 'Ghost', 80), m('Psyshock', 'Psychic', 80), m('Psychic', 'Psychic', 100)],
      art: { shape: 'humanoid', body: '#f7c860', accent: '#b08a48', belly: '#f0d8a0', ears: 'point', earTip: '#b08a48', tail: 'thin', front: ['moustache'], eyes: 'angry', mouth: 'none' } },

    { id: 'gastly', name: 'Gastly', region: 'kanto', dex: 92, types: ['Ghost', 'Poison'],
      hp: 50, atk: 65, def: 30, spd: 80,
      abilities: ['Levitate — ground moves cannot touch it at all', 'Cursed Body — the move that hits it might break'],
      fact: 'It is almost entirely gas — a strong wind can blow it away.',
      moves: [m('Lick', 'Ghost', 30), m('Night Shade', 'Ghost', 50), m('Shadow Ball', 'Ghost', 80), m('Sludge Bomb', 'Poison', 80)],
      art: { shape: 'ghost', body: '#6a5a8a', accent: '#8a7ab0', belly: '#8a7ab0', auraColor: '#b08ad8', ears: 'none', tail: 'none', back: ['aura'], eyes: 'angry', mouth: 'fangs' } },

    { id: 'gengar', name: 'Gengar', region: 'kanto', dex: 94, types: ['Ghost', 'Poison'],
      hp: 90, atk: 100, def: 60, spd: 110,
      abilities: ['Cursed Body — the move that hits it might break', 'Shadow Tag — the other Pokemon cannot run away'],
      fact: 'It hides in your shadow and laughs when you shiver — it just wants someone to play with.',
      moves: [m('Lick', 'Ghost', 30), m('Shadow Claw', 'Ghost', 70), m('Sludge Bomb', 'Poison', 85), m('Shadow Ball', 'Ghost', 90)],
      art: { shape: 'ghost', body: '#6a5a8a', accent: '#4a3a6a', belly: '#7a6a9a', ears: 'point', earTip: '#4a3a6a', tail: 'none', back: ['spikes'], eyes: 'angry', mouth: 'fangs' } },

    { id: 'onix', name: 'Onix', region: 'kanto', dex: 95, types: ['Rock', 'Ground'],
      hp: 75, atk: 65, def: 120, spd: 70,
      abilities: ['Rock Head — hurting itself with a move does no damage', 'Sturdy — it can never be knocked out in one hit'],
      fact: 'It burrows underground at fifty miles an hour, and the tunnels it leaves become homes for others.',
      moves: [m('Rock Throw', 'Rock', 50), m('Bulldoze', 'Ground', 60), m('Rock Slide', 'Rock', 75), m('Earthquake', 'Ground', 100)],
      art: { shape: 'serpent', girth: 23, body: '#a8a8b8', accent: '#88889a', belly: '#c0c0cc', ears: 'none', tail: 'none', front: ['plates'], eyes: 'angry', mouth: 'none' } },

    { id: 'magikarp', name: 'Magikarp', region: 'kanto', dex: 129, types: ['Water'],
      hp: 50, atk: 30, def: 55, spd: 80,
      abilities: ['Swift Swim — it doubles its speed in the rain', 'Rattled — being scared makes it faster'],
      fact: 'It is famously useless and weak — but nobody laughs once it evolves.',
      moves: [m('Splash', 'Normal', 10), m('Tackle', 'Normal', 40), m('Flail', 'Normal', 60), m('Bounce', 'Flying', 85)],
      art: { shape: 'fish', body: '#e8704a', accent: '#f5d76e', belly: '#f5b8a0', ears: 'none', tail: 'none', eyes: 'round', mouth: 'none' } },

    { id: 'gyarados', name: 'Gyarados', region: 'kanto', dex: 130, types: ['Water', 'Flying'],
      hp: 105, atk: 125, def: 79, spd: 81,
      abilities: ['Intimidate — it scares the other Pokemon into hitting softer', 'Moxie — every time it wins it gets stronger'],
      fact: 'Once it appears its rage does not stop until everything around it is flattened.',
      moves: [m('Bite', 'Dark', 60), m('Aqua Tail', 'Water', 90), m('Crunch', 'Dark', 80), m('Hydro Pump', 'Water', 110)],
      art: { shape: 'serpent', girth: 23, body: '#4a90c8', accent: '#f5d76e', belly: '#a8d0e8', ears: 'none', tail: 'none', front: ['crest', 'fangsBig'], eyes: 'angry', mouth: 'fangs' } },

    { id: 'lapras', name: 'Lapras', region: 'kanto', dex: 131, types: ['Water', 'Ice'],
      hp: 130, atk: 85, def: 80, spd: 60,
      abilities: ['Water Absorb — water attacks heal it instead of hurting', 'Shell Armor — it can never be hit by a critical hit'],
      fact: 'It is gentle and clever enough to understand people, and it loves ferrying them across the sea.',
      moves: [m('Water Gun', 'Water', 40), m('Ice Shard', 'Ice', 40), m('Surf', 'Water', 90), m('Ice Beam', 'Ice', 90)],
      art: { shape: 'bigblob', body: '#7fb8d8', accent: '#5f98b8', belly: '#f5e8d8', shell: '#8a98b8', shell2: '#b0c0d8', ears: 'none', tail: 'none', back: ['shell'], front: ['hornPair'], eyes: 'happy', mouth: 'smile' } },

    { id: 'ditto', name: 'Ditto', region: 'kanto', dex: 132, types: ['Normal'],
      hp: 68, atk: 48, def: 48, spd: 48,
      abilities: ['Limber — it can never be paralysed', 'Imposter — it instantly copies the Pokemon it is facing'],
      fact: 'It can rearrange its cells to copy anything it sees — but it gets the face wrong if it is laughing.',
      moves: [m('Pound', 'Normal', 40), m('Tackle', 'Normal', 40), m('Body Slam', 'Normal', 85), m('Take Down', 'Normal', 90)],
      art: { shape: 'blob', body: '#e8a8d8', accent: '#d890c8', belly: '#f0c0e0', ears: 'none', tail: 'none', eyes: 'dot', mouth: 'wave' } },

    /* ---------------- the Eeveelutions ---------------- */
    { id: 'vaporeon', name: 'Vaporeon', region: 'kanto', dex: 134, types: ['Water'],
      hp: 110, atk: 65, def: 60, spd: 65,
      abilities: ['Water Absorb — water attacks heal it instead of hurting', 'Hydration — rain washes away anything making it ill'],
      fact: 'Its cells are so like water that it can melt into the sea and disappear completely.',
      moves: [m('Water Gun', 'Water', 40), m('Bite', 'Dark', 60), m('Surf', 'Water', 90), m('Hydro Pump', 'Water', 110)],
      art: { shape: 'quad', body: '#7fc0e8', accent: '#5fa0c8', belly: '#f5f0d8', ears: 'fin', earTip: '#f5f0d8', tail: 'fan', front: ['gills'], eyes: 'round', mouth: 'smile' } },

    { id: 'jolteon', name: 'Jolteon', region: 'kanto', dex: 135, types: ['Electric'],
      hp: 65, atk: 65, def: 60, spd: 130,
      abilities: ['Volt Absorb — electric attacks heal it instead of hurting', 'Quick Feet — feeling poorly makes it faster'],
      fact: 'Its fur is made of tiny needles it can fire like arrows when it gets cross.',
      moves: [m('Thunder Shock', 'Electric', 40), m('Quick Attack', 'Normal', 40), m('Discharge', 'Electric', 80), m('Thunderbolt', 'Electric', 90)],
      art: { shape: 'quad', body: '#f7d060', accent: '#e0b840', belly: '#f5f0d8', ears: 'point', earTip: '#e0b840', tail: 'thin', back: ['spikes'], eyes: 'angry', mouth: 'none' } },

    { id: 'flareon', name: 'Flareon', region: 'kanto', dex: 136, types: ['Fire'],
      hp: 65, atk: 130, def: 60, spd: 65,
      abilities: ['Flash Fire — fire attacks make it stronger, not weaker', 'Guts — feeling poorly makes it punch harder'],
      fact: 'It stores fire in a pouch inside it — its body runs hotter than a bonfire.',
      moves: [m('Ember', 'Fire', 40), m('Bite', 'Dark', 60), m('Flame Charge', 'Fire', 50), m('Flare Blitz', 'Fire', 110)],
      art: { shape: 'quad', body: '#e8704a', accent: '#c85a38', belly: '#f5d76e', mane: '#f5e0b0', ears: 'point', earTip: '#c85a38', tail: 'bushy', front: ['mane'], eyes: 'round', mouth: 'smile' } },

    /* ---------------- the big ones ---------------- */
    { id: 'snorlax', name: 'Snorlax', region: 'kanto', dex: 143, types: ['Normal'],
      hp: 160, atk: 110, def: 65, spd: 30,
      abilities: ['Immunity — it can never be poisoned', 'Thick Fat — fire and ice attacks hurt it only half as much'],
      fact: 'It eats 900 pounds of food a day and then falls asleep — kids use its belly as a trampoline.',
      moves: [m('Headbutt', 'Normal', 70), m('Body Slam', 'Normal', 85), m('Crunch', 'Dark', 80), m('Giga Impact', 'Normal', 110)],
      art: { shape: 'bigblob', body: '#3f6f8a', accent: '#2f5a70', belly: '#f5e8c8', ears: 'none', tail: 'none', eyes: 'sleepy', mouth: 'none' } },

    { id: 'articuno', name: 'Articuno', region: 'kanto', dex: 144, types: ['Ice', 'Flying'], legend: true,
      hp: 110, atk: 95, def: 100, spd: 85,
      abilities: ['Pressure — the Pokemon facing it gets tired faster', 'Snow Cloak — it is hard to hit in a snowstorm'],
      fact: 'It is said to appear to travellers lost in icy mountains, and snow falls where it flies.',
      moves: [m('Ice Shard', 'Ice', 40), m('Air Slash', 'Flying', 75), m('Ice Beam', 'Ice', 90), m('Blizzard', 'Ice', 110)],
      art: { shape: 'bird', body: '#7fd8f0', accent: '#4a90c8', belly: '#d8f0fa', beak: '#8ab8d8', wing: '#5fb8e0', ears: 'none', tail: 'fan', back: ['bigWings'], front: ['beak', 'crest'], eyes: 'round', mouth: 'none' } },

    { id: 'zapdos', name: 'Zapdos', region: 'kanto', dex: 145, types: ['Electric', 'Flying'], legend: true,
      hp: 110, atk: 110, def: 85, spd: 100,
      abilities: ['Pressure — the Pokemon facing it gets tired faster', 'Static — anyone who touches it might get zapped'],
      fact: 'It lives in thunderclouds, and it gains power every time lightning strikes it.',
      moves: [m('Thunder Shock', 'Electric', 40), m('Drill Peck', 'Flying', 80), m('Thunderbolt', 'Electric', 90), m('Thunder', 'Electric', 110)],
      art: { shape: 'bird', body: '#f7d02c', accent: '#e0a600', belly: '#fff0a0', beak: '#e8a020', wing: '#f5c020', ears: 'none', tail: 'fan', back: ['bigWings', 'spikes'], front: ['beak', 'crest'], eyes: 'angry', mouth: 'none' } },

    { id: 'moltres', name: 'Moltres', region: 'kanto', dex: 146, types: ['Fire', 'Flying'], legend: true,
      hp: 110, atk: 115, def: 90, spd: 90,
      abilities: ['Pressure — the Pokemon facing it gets tired faster', 'Flame Body — touching it can set an attacker alight'],
      fact: 'Its wings shimmer with flame, and it heals itself by bathing in a volcano.',
      moves: [m('Ember', 'Fire', 40), m('Air Slash', 'Flying', 75), m('Flamethrower', 'Fire', 90), m('Fire Blast', 'Fire', 110)],
      art: { shape: 'bird', body: '#f0863a', accent: '#f5b700', belly: '#ffd9a0', beak: '#e8a020', wing: '#f5a020', ears: 'none', tail: 'fan', back: ['bigWings', 'backFlames'], front: ['beak', 'headTuft'], eyes: 'angry', mouth: 'none' } },

    { id: 'dragonair', name: 'Dragonair', region: 'kanto', dex: 148, types: ['Dragon'],
      hp: 78, atk: 84, def: 65, spd: 70,
      abilities: ['Shed Skin — it can shed its skin to heal itself', 'Marvel Scale — its scales harden when it feels ill'],
      fact: 'The crystal orbs on its neck let it change the weather — farmers say it brings the rain.',
      moves: [m('Twister', 'Dragon', 40), m('Aqua Tail', 'Water', 90), m('Dragon Pulse', 'Dragon', 85), m('Ice Beam', 'Ice', 85)],
      art: { shape: 'serpent', body: '#7fb8e8', accent: '#5f98c8', belly: '#f0f8ff', cheek: '#7fd0f0', ears: 'fin', earTip: '#ffffff', tail: 'none', front: ['gem', 'tailOrbs'], eyes: 'sleepy', mouth: 'none' } },

    { id: 'dragonite', name: 'Dragonite', region: 'kanto', dex: 149, types: ['Dragon', 'Flying'],
      hp: 111, atk: 134, def: 95, spd: 80,
      abilities: ['Inner Focus — it never flinches', 'Multiscale — at full health, everything hurts it half as much'],
      fact: 'It can fly around the whole world in sixteen hours, and it rescues people lost at sea.',
      moves: [m('Dragon Claw', 'Dragon', 80), m('Wing Attack', 'Flying', 60), m('Dragon Rush', 'Dragon', 100), m('Hurricane', 'Flying', 100)],
      art: { shape: 'biped', body: '#f5c86e', accent: '#e0a840', belly: '#f0e0b0', wing: '#7fc0a8', ears: 'none', tail: 'thin', back: ['bigWings'], front: ['hornPair'], eyes: 'happy', mouth: 'smile' } },

    { id: 'mewtwo', name: 'Mewtwo', region: 'kanto', dex: 150, types: ['Psychic'], legend: true,
      hp: 116, atk: 144, def: 90, spd: 130,
      abilities: ['Pressure — the Pokemon facing it gets tired faster', 'Unnerve — the other Pokemon is too nervous to eat its berry'],
      fact: 'It was made in a laboratory from Mew, and its psychic power is the strongest ever measured.',
      moves: [m('Confusion', 'Psychic', 50), m('Shadow Ball', 'Ghost', 80), m('Aura Sphere', 'Fighting', 80), m('Psystrike', 'Psychic', 120)],
      art: { shape: 'humanoid', body: '#e8e0f0', accent: '#a890c8', belly: '#f5f0fa', auraColor: '#c8a8f0', ears: 'point', earTip: '#a890c8', tail: 'thin', back: ['aura'], eyes: 'angry', mouth: 'none' } },

    { id: 'mew', name: 'Mew', region: 'kanto', dex: 151, types: ['Psychic'], legend: true,
      hp: 110, atk: 100, def: 100, spd: 100,
      abilities: ['Synchronize — whatever bad thing happens to it happens to the attacker too', 'Learn Anything — it can use every move there is'],
      fact: 'It is so shy it stays invisible, and every single Pokemon move can be learned by it.',
      moves: [m('Pound', 'Normal', 40), m('Psychic', 'Psychic', 90), m('Aura Sphere', 'Fighting', 80), m('Ancient Power', 'Rock', 60)],
      art: { shape: 'humanoid', body: '#f7b8d8', accent: '#e898c0', belly: '#ffd8e8', ears: 'point', earTip: '#e898c0', tail: 'thin', back: ['sparkles'], eyes: 'happy', mouth: 'smile' } }
  ]);

  /* =========================================================================
     Evolution lines. Ones we don't have a card for still show up greyed,
     so the chain makes sense (Pidgey → Pidgeotto → Pidgeot).
     ========================================================================= */
  window.DEX.addChains([
    /* Kanto */
    ['bulbasaur', 'ivysaur', 'venusaur'],
    ['charmander', 'charmeleon', 'charizard'],
    ['squirtle', 'wartortle', 'blastoise'],
    ['pichu', 'pikachu', 'raichu'],
    ['pidgey', 'pidgeotto', 'pidgeot'],
    ['vulpix', 'ninetales'],
    ['jigglypuff', 'wigglytuff'],
    ['meowth', 'persian'],
    ['psyduck', 'golduck'],
    ['growlithe', 'arcanine'],
    ['machop', 'machoke', 'machamp'],
    ['abra', 'kadabra', 'alakazam'],
    ['gastly', 'haunter', 'gengar'],
    ['onix', 'steelix'],
    ['magikarp', 'gyarados'],
    ['dratini', 'dragonair', 'dragonite'],
    { label: 'Eevee can become', ids: ['eevee', 'vaporeon', 'jolteon', 'flareon', 'espeon', 'umbreon', 'leafeon', 'glaceon', 'sylveon'] },
    /* Johto */
    ['chikorita', 'bayleef', 'meganium'],
    ['cyndaquil', 'quilava', 'typhlosion'],
    ['totodile', 'croconaw', 'feraligatr'],
    ['togepi', 'togetic', 'togekiss'],
    ['marill', 'azumarill'],
    ['mareep', 'flaaffy', 'ampharos'],
    ['larvitar', 'pupitar', 'tyranitar'],
    /* Hoenn */
    ['treecko', 'grovyle', 'sceptile'],
    ['torchic', 'combusken', 'blaziken'],
    ['mudkip', 'marshtomp', 'swampert'],
    ['ralts', 'kirlia', 'gardevoir'],
    /* Sinnoh */
    ['turtwig', 'grotle', 'torterra'],
    ['chimchar', 'monferno', 'infernape'],
    ['piplup', 'prinplup', 'empoleon'],
    ['shinx', 'luxio', 'luxray'],
    ['buneary', 'lopunny'],
    ['riolu', 'lucario'],
    ['gible', 'gabite', 'garchomp'],
    /* Unova */
    ['snivy', 'servine', 'serperior'],
    ['tepig', 'pignite', 'emboar'],
    ['oshawott', 'dewott', 'samurott'],
    ['axew', 'fraxure', 'haxorus'],
    ['zorua', 'zoroark'],
    ['deerling', 'sawsbuck'],
    /* Kalos */
    ['chespin', 'quilladin', 'chesnaught'],
    ['fennekin', 'braixen', 'delphox'],
    ['froakie', 'frogadier', 'greninja'],
    ['pancham', 'pangoro'],
    /* Alola */
    ['rowlet', 'trumbeak', 'decidueye'],
    ['litten', 'torracat', 'incineroar'],
    ['popplio', 'brionne', 'primarina'],
    ['rockruff', 'lycanroc'],
    /* Galar */
    ['grookey', 'thwackey', 'rillaboom'],
    ['scorbunny', 'raboot', 'cinderace'],
    ['sobble', 'drizzile', 'inteleon'],
    ['wooloo', 'dubwool'],
    ['yamper', 'boltund'],
    ['dreepy', 'drakloak', 'dragapult'],
    /* Paldea */
    ['sprigatito', 'floragato', 'meowscarada'],
    ['fuecoco', 'crocalor', 'skeledirge'],
    ['quaxly', 'quaxwell', 'quaquaval'],
    ['pawmi', 'pawmo', 'pawmot'],
    ['lechonk', 'oinkologne'],
    ['tinkatink', 'tinkatuff', 'tinkaton'],
    ['maschiff', 'mabosstiff']
  ]);
})();
